# Generated by Django 5.0.6 on 2024-07-06 12:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("offers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="offer",
            name="active",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="offer",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
