# Generated by Django 5.0.6 on 2024-07-06 14:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("offers", "0003_alter_location_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="offer",
            name="source",
            field=models.CharField(
                choices=[("olx", "olx"), ("otomoto", "otomoto")],
                default="olx",
                max_length=30,
            ),
            preserve_default=False,
        ),
    ]
